In [3]:
import duckdb

In [4]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [5]:
df = con.execute("SELECT * FROM produtos").fetch_df()
df.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_unitario
0  10002    MARTELO         BT10            100         99.0
1  10001   PARAFUSO         BT10            100        100.0
2  10003      CHAVE         BT10            100         50.0
3  10004      PREGO         BT10            100         70.0
4  10005   LIMADORA         BT10            100         70.0

In [6]:
# criar uma dimensão de categorias
df2 = df.drop(columns=['id_categoria', 'id_fornecedor'])
df2.head(10)

      id nm_produto  vl_unitario
0  10002    MARTELO         99.0
1  10001   PARAFUSO        100.0
2  10003      CHAVE         50.0
3  10004      PREGO         70.0
4  10005   LIMADORA         70.0

In [7]:
# criar tabela e inserir dados
con.execute("""
    CREATE TABLE IF NOT EXISTS dim_produtos (
        id_produto BIGINT,
        nm_produto TEXT,
        vl_unitario FLOAT
    )
""")

In [9]:
con.execute("""
    INSERT INTO dim_produtos select * from df2
""")

In [10]:
df_dim = con.execute("SELECT * FROM dim_produtos").fetch_df()
df_dim.head(10)

   id_produto nm_produto  vl_unitario
0       10002    MARTELO         99.0
1       10001   PARAFUSO        100.0
2       10003      CHAVE         50.0
3       10004      PREGO         70.0
4       10005   LIMADORA         70.0

In [11]:
con.close()